# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bethany Baptist Church
email: secretary@bethanybaptistchurch.ca
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Bethany Baptist Church located at 382 Centrepointe Drive, Ottawa ON, K2G 6A1!
  Discover a welcoming community dedicated to worship, fellowship, and spiritual growth.
  Our church is committed to spreading the love of Christ and serving the Ottawa community.
  Join us for inspiring worship services, engaging activities, and meaningful connections.
  Explore our website to learn more about our mission, ministries, and upcoming events.
  Bethany Baptist Church - where faith, community, and compassion come together.
# twitter_username: username
# github_username: username
minimal_mistakes_skin: default
search: true
breadcrumbs: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Toronto

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: | 
    Rev. Dr. Victor Lujetic
  #avatar : "/assets/images/bio-photo.jpg"
  bio: | 
    **Worship Service**
    * Every Sunday at 10 a.m.
    
    **Communion**
    * First Sunday of the month.
    
    **Address**
    * 382 Centrepointe Drive, Ottawa ON, K2G 6A1
    
    **Office Hours**
    * 9:00 a.m. to 1:00 p.m.
    * Monday to Friday
    * Closed public holidays
    
  links:
    - label: "613-224-5611"
      icon: "fas fa-phone-alt"
      url: ""
    - label: "secretary@bethanybaptistchurch.ca"
      icon: "fas fa-envelope"
      url: "mailto:secretary@bethanybaptistchurch.ca"

footer:
  links:
    - label: "CBOQ"
      icon: "fas fa-church"
      url: "https://baptist.ca/"
      
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      show_date: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
